In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.io as scp
import math
import statistics
import seaborn as sns
import sklearn

from matplotlib.patches import Polygon
from scipy.stats import anderson
from scipy.stats import shapiro
from scipy import stats
from statistics import stdev
from numpy.random import randn
from numpy.random import seed
from scipy.stats import spearmanr
from scipy.stats import pearsonr

#from sklearn import linear_model
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error


import numpy as np
from sklearn.decomposition import PCA

In [2]:
from __future__ import print_function
from __future__ import division

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
import statsmodels.api as sm
from warnings import filterwarnings

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.tools import eval_measures
from sklearn.model_selection import train_test_split


filterwarnings('ignore')

In [3]:
datainput = pd.read_csv("final_data_file.csv")

In [4]:
datainput = datainput.iloc[: , 1:]

In [5]:
#datainput[["item_id", "dept_id","cat_id","store_id","state_id","d"]] = datainput[["item_id", "dept_id","cat_id","store_id","state_id","d"]].apply(pd.to_numeric)

In [6]:
for col in ["item_id", "dept_id","cat_id","store_id","state_id","d"]:
    datainput[col] = datainput[col].astype('category')

In [7]:
for i in datainput.columns:
    if str(datainput[i].dtype)=='category':
        datainput[i] = datainput[i].cat.codes

In [8]:
datainput

,item_id,dept_id,cat_id,store_id,state_id,d,sales,wday,month,year,weekend
0,1437,3,1,0,0,0,0,1,1,2011,1
1,1438,3,1,0,0,0,0,1,1,2011,1
2,1439,3,1,0,0,0,0,1,1,2011,1
3,1440,3,1,0,0,0,0,1,1,2011,1
4,1441,3,1,0,0,0,0,1,1,2011,1
...,...,...,...,...,...,...,...,...,...,...,...
59181085,1432,2,0,9,2,1047,1,2,5,2016,1
59181086,1433,2,0,9,2,1047,0,2,5,2016,1
59181087,1434,2,0,9,2,1047,2,2,5,2016,1
59181088,1435,2,0,9,2,1047,0,2,5,2016,1
59181089,1436,2,0,9,2,1047,1,2,5,2016,1

In [9]:
xOriginal = datainput[["item_id", "dept_id","cat_id","store_id","state_id","d","wday","month","year","weekend"]].to_numpy()
yOriginal = datainput[["sales"]].to_numpy()

xTrain = xOriginal[int(len(xOriginal) * 0) : int(len(xOriginal) * .80)]
yTrain = yOriginal[int(len(yOriginal) * 0) : int(len(yOriginal) * .80)]

In [10]:
xTest = xOriginal[int(len(xOriginal) * .80) : int(len(xOriginal) * 1.00)]
yTest = yOriginal[int(len(yOriginal) * .80) : int(len(yOriginal) * 1.00)]

In [11]:
poisson_model = linear_model.PoissonRegressor()
poisson_model.fit(xTrain, yTrain)

y_pred_model = poisson_model.predict(xTest)


print("Coefficients: \n", poisson_model)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(yTest, y_pred_model))
print("Mean absoulte error: %.2f" % mean_absolute_error(yTest, y_pred_model))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(yTest, y_pred_model))

Coefficients:
 PoissonRegressor()
Mean squared error: 13.03
Mean absoulte error: 1.54
Coefficient of determination: 0.01